name: db-benchmark

services:
  mysql:
    image: mysql:8.0
    command: --max-allowed-packet=96M --character-set-server=utf8mb4 --log-bin-trust-function-creators=1 --local-infile=1 --max-connections=1000
    cpu_count: 4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sb_test
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
      - type: tmpfs
        target: /tmp

  # postgres:
  #   image: postgres:13.3
  #   cpu_count: 4
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: benchmark
  #   volumes:
  #     - type: tmpfs
  #       target: /var/lib/postgresql/data

  sysbench:
    image: ubuntu:latest
    entrypoint: "/bin/bash"
    #command: -c 'apt update; apt install -y sysbench; time sysbench --threads=2 --events=4 --cpu-max-prime=100500 --verbosity=0 cpu run'
    command: -c 'apt update; apt install -y sysbench; sleep 86400s'
    cpu_count: 4
