name: db-benchmark

services:
  # https://dev.mysql.com/doc/refman/8.0/en/server-options.html
  mysql:
    image: mysql:8.0.31
    command: --max-allowed-packet=96M --character-set-server=utf8mb4 --log-bin-trust-function-creators=1 --local-infile=1 --max-connections=1000 --innodb-buffer-pool-size=2415919104 --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=O_DIRECT_NO_FSYNC --innodb-doublewrite=OFF
    cpus: 4
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sb_test
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
      - type: tmpfs
        target: /tmp

  # https://mariadb.com/kb/en/mysqld-options/
  mariadb:
    image: mariadb:10.10
    command: --max-allowed-packet=96M --character-set-server=utf8mb4 --log-bin-trust-function-creators=1 --local-infile=1 --max-connections=1000 --innodb-buffer-pool-size=2415919104 --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=O_DIRECT --innodb-doublewrite=OFF
    cpus: 4
    ports:
      - "3316:3306"
    environment:
      MARIADB_DATABASE: sb_test
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
      - type: tmpfs
        target: /tmp

  postgres:
    image: postgres:13.3
    cpus: 4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sb_test
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    cpus: 4
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: Password_
      ACCEPT_EULA: "Y"

  sysbench:
    image: ubuntu:latest
    entrypoint: "/bin/bash"
    command: -c 'apt update; apt install -y sysbench; echo ready; sleep 86400s'
    cpus: 4

  hammerdb:
    image: tpcorg/hammerdb:v4.6
    entrypoint: "/bin/bash"
    command: -c 'apt update; apt install -y msodbcsql18; ln -sf /etc/odbcinst.ini /usr/local/unixODBC/etc/odbcinst.ini; echo ready; sleep 86400s'
    cpus: 4
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./hammerdb/mssql_run.py/:/home/hammerdb/HammerDB-4.6/mssql_run.py
      - ./hammerdb/mssql_schema.py/:/home/hammerdb/HammerDB-4.6/mssql_schema.py
